//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Controls;

public class ball
{
	public virtual object owner
	{
		get;
		set;
	}

	public ContentControl ballObject
	{
		get;
		set;
	}

    public double xspeed;
    public double yspeed;
    public int xdirection;
    public int ydirection;
    public double ballSpeed;
    public ball(ContentControl ballobject, double XSpeedToSpawnWith, double YSpeedToSpawnWith, int XDirectionToSpawnWith, int YDirectionToSpawnWith, double ballSpeedToSpawnWith)
	{
        ballObject = ballobject;
        xspeed = XSpeedToSpawnWith;
        yspeed = YSpeedToSpawnWith;
        xdirection = XDirectionToSpawnWith;
        ydirection = YDirectionToSpawnWith;
        ballSpeed = ballSpeedToSpawnWith;
	}
}

