//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Controls;

public class ball
{
	public virtual object owner
	{
		get;
		set;
	}

	private ContentControl ballObject
	{
		get;
		set;
	}

    private double xspeed;
    private double yspeed;
    private int xdirection;
    private int ydirection;
    public ball(ContentControl ballobject, double XSpeedToSpawnWith, double YSpeedToSpawnWith, int XDirectionToSpawnWith, int YDirectionToSpawnWith)
	{
        ballObject = ballobject;
        xspeed = XSpeedToSpawnWith;
        yspeed = YSpeedToSpawnWith;
        xdirection = XDirectionToSpawnWith;
        ydirection = YDirectionToSpawnWith;
	}
}

