//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class difficulty
{
	public difficulty(int difficulty)
	{
        switch (difficulty)
        {
            case 1:
                descendSpeed = 0.05;
                dropRate = 0.25;
                break;
            case 2:
                descendSpeed = 0.075;
                dropRate = 0.125;
                break;
            case 3:
                descendSpeed = 0.1;
                dropRate = 0.1;
                break;

        }
	}

	public double descendSpeed
	{
		get;
		set;
	}

	public double dropRate
	{
		get;
		set;
	}

}

