//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class difficulty
{
	public string _difficulty
	{
		get;
		set;
	}

	public virtual object descendSpeed
	{
		get;
		set;
	}

	public virtual object dropRate
	{
		get;
		set;
	}

}

