using dxballslib;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;


public class drops
{
    //Falling objects that give certain buffs or points
    public ContentControl DropObject;
    public string typeOfDrop;
    public int dropSpeed = 5;
    private buffs _buff;
    private debuffs _debuff;
    private int? _points;
    private int? _lives;
    public buffs Buff
    {
        get
        {
            return _buff;
        }
    }

    public debuffs DeBuff
    {
        get
        {
            return _debuff;
        }
    }
    public int? Points
    {
        get
        {
            return _points;
        }
    }
    public int? lives
    {
        get
        {
            return _lives;
        }
    }
    
    public drops(ContentControl drop, string type, int? points = null, buffs buffs = null, debuffs debuffs = null, int? lives = null)
    {
        //Når man skriver et parameter i en constructor med f.eks. = null, så er parametren optional, og så kan du tjekke nede i hitPlayer() om hvad den skal...
        DropObject = drop;
        typeOfDrop = type;
        _buff = buffs;
        _debuff = debuffs;
        _points = points;
        _lives = lives;
    }
    public drops()
    {

    }
    public string hitPlayer()
    {
        //Player has been hit - find what to do with the guy...
        if (this.Buff != null)
        {
            return "BUFF";
        }
        if (this.DeBuff != null)
        {
            return "DEBUFF";
        }
        if (this.Points != null)
        {
            if (this.Points.HasValue)
            {
                return "POINTBONUS";
            }
            //Give the player points
        }
        if (this.lives != null)
        {
            if (this.lives.HasValue)
            {
                return "LIFEBONUS";
            }
        }
        return null;
    }
}

