//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class enemyBlock
{
	private object color
	{
		get;
		set;
	}

	public virtual void death()
	{
		throw new System.NotImplementedException();
	}

	private void dropRandomItem()
	{
		throw new System.NotImplementedException();
	}

}

