//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class main
{
	public virtual object enemyList<list>
	{
		get;
		set;
	}

	public virtual object ballList<list>
	{
		get;
		set;
	}

	public virtual object amountOfBalls
	{
		get;
		set;
	}

	public virtual object Score
	{
		get;
		set;
	}

	private void addPlayer()
	{
		throw new System.NotImplementedException();
	}

	public virtual void addEnemy()
	{
		throw new System.NotImplementedException();
	}

	public virtual void addBall()
	{
		throw new System.NotImplementedException();
	}

}

