//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// event listeners for movement
/// 
/// </remarks>
public class player
{
	private object playerPictureBox
	{
		get;
		set;
	}

	public virtual object playerNumber
	{
		get;
		set;
	}

	public virtual object speed
	{
		get;
		set;
	}

	public virtual void move(string leftOrRight)
	{
		throw new System.NotImplementedException();
	}

}

