//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Controls;

/// <remarks>
/// event listeners for movement
/// 
/// </remarks>
public class player
{
    public player(ContentControl PlayerBlock, int PlayerNumber, int Speed)
    {
        playerBlock = PlayerBlock;
        playerNumber = PlayerNumber;
        speed = Speed;
    }
	public ContentControl playerBlock
	{
		get;
		set;
	}

	public int playerNumber
	{
		get;
		set;
	}

	public int speed
	{
		get;
		set;
	}

	public void move(string leftOrRight)
	{
        if (leftOrRight == "LEFT")
        {
            Canvas.SetLeft(playerBlock, (Canvas.GetLeft(playerBlock) - speed));
        }
        else if(leftOrRight == "RIGHT")
        {
            Canvas.SetLeft(playerBlock, (Canvas.GetLeft(playerBlock) + speed));
        }
	}

}

